FROM oven/bun:1.3.11
WORKDIR /app
COPY package.json bun.lock turbo.json tsconfig.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/scripts/package.json apps/scripts/package.json
COPY packages/auth/package.json packages/auth/package.json
COPY packages/cache/package.json packages/cache/package.json
COPY packages/contracts/package.json packages/contracts/package.json
COPY packages/database/package.json packages/database/package.json
COPY packages/resource_manager/package.json packages/resource_manager/package.json
RUN bun install --frozen-lockfile

COPY . .
WORKDIR /app/apps/api
EXPOSE 3000
CMD ["bun", "src/main.ts"]
